[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
fake = "4.0.0"
iced = { version = "0.13.1", features = ["canvas", "advanced"] }
screen_size = "0.1.0"
serde_json = "1.0.140"
smol_str = "0.2.2"
serde = { version = "1.0.217", features = ["derive"] }
rdev = "0.5.3"
