[package]
name = "visual"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["canvas", "advanced"] }
windows_operations = {path = "../windows_operations"}
serde = { version = "1.0.217", features = ["derive"] }
