#[macro_export]
macro_rules! key_queue {
    () => {
        vec![
            // Three-character combinations (full reverse order)
            "hhh", "hha", "hhg", "hhs", "hhl", "hhd", "hhk", "hhf", "hhj", "hah", "haa", "hag",
            "has", "hal", "had", "hak", "haf", "haj", "hgh", "hga", "hgg", "hgs", "hgl", "hgd",
            "hgk", "hgf", "hgj", "hsh", "hsa", "hsg", "hss", "hsl", "hsd", "hsk", "hsf", "hsj",
            "hlh", "hla", "hlg", "hls", "hll", "hld", "hlk", "hlf", "hlj", "hdh", "hda", "hdg",
            "hds", "hdl", "hdd", "hdk", "hdf", "hdj", "hkh", "hka", "hkg", "hks", "hkl", "hkd",
            "hkk", "hkf", "hkj", "hfh", "hfa", "hfg", "hfs", "hfl", "hfd", "hfk", "hff", "hfj",
            "hjh", "hja", "hjg", "hjs", "hjl", "hjd", "hjk", "hjf", "hjj", "ahh", "aha", "ahg",
            "ahs", "ahl", "ahd", "ahk", "ahf", "ahj", "aah", "aaa", "aag", "aas", "aal", "aad",
            "aak", "aaf", "aaj", "agh", "aga", "agg", "ags", "agl", "agd", "agk", "agf", "agj",
            "ash", "asa", "asg", "ass", "asl", "asd", "ask", "asf", "asj", "alh", "ala", "alg",
            "als", "all", "ald", "alk", "alf", "alj", "adh", "ada", "adg", "ads", "adl", "add",
            "adk", "adf", "adj", "akh", "aka", "akg", "aks", "akl", "akd", "akk", "akf", "akj",
            "afh", "afa", "afg", "afs", "afl", "afd", "afk", "aff", "afj", "ajh", "aja", "ajg",
            "ajs", "ajl", "ajd", "ajk", "ajf", "ajj", "ghh", "gha", "ghg", "ghs", "ghl", "ghd",
            "ghk", "ghf", "ghj", "gah", "gaa", "gag", "gas", "gal", "gad", "gak", "gaf", "gaj",
            "ggh", "gga", "ggg", "ggs", "ggl", "ggd", "ggk", "ggf", "ggj", "gsh", "gsa", "gsg",
            "gss", "gsl", "gsd", "gsk", "gsf", "gsj", "glh", "gla", "glg", "gls", "gll", "gld",
            "glk", "glf", "glj", "gdh", "gda", "gdg", "gds", "gdl", "gdd", "gdk", "gdf", "gdj",
            "gkh", "gka", "gkg", "gks", "gkl", "gkd", "gkk", "gkf", "gkj", "gfh", "gfa", "gfg",
            "gfs", "gfl", "gfd", "gfk", "gff", "gfj", "gjh", "gja", "gjg", "gjs", "gjl", "gjd",
            "gjk", "gjf", "gjj", "shh", "sha", "shg", "shs", "shl", "shd", "shk", "shf", "shj",
            "sah", "saa", "sag", "sas", "sal", "sad", "sak", "saf", "saj", "sgh", "sga", "sgg",
            "sgs", "sgl", "sgd", "sgk", "sgf", "sgj", "ssh", "ssa", "ssg", "sss", "ssl", "ssd",
            "ssk", "ssf", "ssj", "slh", "sla", "slg", "sls", "sll", "sld", "slk", "slf", "slj",
            "sdh", "sda", "sdg", "sds", "sdl", "sdd", "sdk", "sdf", "sdj", "skh", "ska", "skg",
            "sks", "skl", "skd", "skk", "skf", "skj", "sfh", "sfa", "sfg", "sfs", "sfl", "sfd",
            "sfk", "sff", "sfj", "sjh", "sja", "sjg", "sjs", "sjl", "sjd", "sjk", "sjf", "sjj",
            "lhh", "lha", "lhg", "lhs", "lhl", "lhd", "lhk", "lhf", "lhj", "lah", "laa", "lag",
            "las", "lal", "lad", "lak", "laf", "laj", "lgh", "lga", "lgg", "lgs", "lgl", "lgd",
            "lgk", "lgf", "lgj", "lsh", "lsa", "lsg", "lss", "lsl", "lsd", "lsk", "lsf", "lsj",
            "llh", "lla", "llg", "lls", "lll", "lld", "llk", "llf", "llj", "ldh", "lda", "ldg",
            "lds", "ldl", "ldd", "ldk", "ldf", "ldj", "lkh", "lka", "lkg", "lks", "lkl", "lkd",
            "lkk", "lkf", "lkj", "lfh", "lfa", "lfg", "lfs", "lfl", "lfd", "lfk", "lff", "lfj",
            "ljh", "lja", "ljg", "ljs", "ljl", "ljd", "ljk", "ljf", "ljj", "dhh", "dha", "dhg",
            "dhs", "dhl", "dhd", "dhk", "dhf", "dhj", "dah", "daa", "dag", "das", "dal", "dad",
            "dak", "daf", "daj", "dgh", "dga", "dgg", "dgs", "dgl", "dgd", "dgk", "dgf", "dgj",
            "dsh", "dsa", "dsg", "dss", "dsl", "dsd", "dsk", "dsf", "dsj", "dlh", "dla", "dlg",
            "dls", "dll", "dld", "dlk", "dlf", "dlj", "ddh", "dda", "ddg", "dds", "ddl", "ddd",
            "ddk", "ddf", "ddj", "dkh", "dka", "dkg", "dks", "dkl", "dkd", "dkk", "dkf", "dkj",
            "dfh", "dfa", "dfg", "dfs", "dfl", "dfd", "dfk", "dff", "dfj", "djh", "dja", "djg",
            "djs", "djl", "djd", "djk", "djf", "djj", "khh", "kha", "khg", "khs", "khl", "khd",
            "khk", "khf", "khj", "kah", "kaa", "kag", "kas", "kal", "kad", "kak", "kaf", "kaj",
            "kgh", "kga", "kgg", "kgs", "kgl", "kgd", "kgk", "kgf", "kgj", "ksh", "ksa", "ksg",
            "kss", "ksl", "ksd", "ksk", "ksf", "ksj", "klh", "kla", "klg", "kls", "kll", "kld",
            "klk", "klf", "klj", "kdh", "kda", "kdg", "kds", "kdl", "kdd", "kdk", "kdf", "kdj",
            "kkh", "kka", "kkg", "kks", "kkl", "kkd", "kkk", "kkf", "kkj", "kfh", "kfa", "kfg",
            "kfs", "kfl", "kfd", "kfk", "kff", "kfj", "kjh", "kja", "kjg", "kjs", "kjl", "kjd",
            "kjk", "kjf", "kjj", "fhh", "fha", "fhg", "fhs", "fhl", "fhd", "fhk", "fhf", "fhj",
            "fah", "faa", "fag", "fas", "fal", "fad", "fak", "faf", "faj", "fgh", "fga", "fgg",
            "fgs", "fgl", "fgd", "fgk", "fgf", "fgj", "fsh", "fsa", "fsg", "fss", "fsl", "fsd",
            "fsk", "fsf", "fsj", "flh", "fla", "flg", "fls", "fll", "fld", "flk", "flf", "flj",
            "fdh", "fda", "fdg", "fds", "fdl", "fdd", "fdk", "fdf", "fdj", "fkh", "fka", "fkg",
            "fks", "fkl", "fkd", "fkk", "fkf", "fkj", "ffh", "ffa", "ffg", "ffs", "ffl", "ffd",
            "ffk", "fff", "ffj", "fjh", "fja", "fjg", "fjs", "fjl", "fjd", "fjk", "fjf", "fjj",
            "jhh", "jha", "jhg", "jhs", "jhl", "jhd", "jhk", "jhf", "jhj", "jah", "jaa", "jag",
            "jas", "jal", "jad", "jak", "jaf", "jaj", "jgh", "jga", "jgg", "jgs", "jgl", "jgd",
            "jgk", "jgf", "jgj", "jsh", "jsa", "jsg", "jss", "jsl", "jsd", "jsk", "jsf", "jsj",
            "jlh", "jla", "jlg", "jls", "jll", "jld", "jlk", "jlf", "jlj", "jdh", "jda", "jdg",
            "jds", "jdl", "jdd", "jdk", "jdf", "jdj", "jkh", "jka", "jkg", "jks", "jkl", "jkd",
            "jkk", "jkf", "jkj", "jfh", "jfa", "jfg", "jfs", "jfl", "jfd", "jfk", "jff", "jfj",
            "jjh", "jja", "jjg", "jjs", "jjl", "jjd", "jjk", "jjf", "jjj",
            // Two-character combinations (reverse order)
            "hh", "ha", "hg", "hs", "hl", "hd", "hk", "hf", "hj", "ah", "aa", "ag", "as", "al",
            "ad", "ak", "af", "aj", "gh", "ga", "gg", "gs", "gl", "gd", "gk", "gf", "gj", "sh",
            "sa", "sg", "ss", "sl", "sd", "sk", "sf", "sj", "lh", "la", "lg", "ls", "ll", "ld",
            "lk", "lf", "lj", "dh", "da", "dg", "ds", "dl", "dd", "dk", "df", "dj", "kh", "ka",
            "kg", "ks", "kl", "kd", "kk", "kf", "kj", "fh", "fa", "fg", "fs", "fl", "fd", "fk",
            "ff", "fj", "jh", "ja", "jg", "js", "jl", "jd", "jk", "jf", "jj",
            // Single characters (reverse order)
            "h", "a", "g", "s", "l", "d", "k", "f", "j",
        ]
    };
}
